"use client";
import React, { useState } from "react";
import { ArrowRight, Eye, EyeOff, X } from "lucide-react";
export type Account = { name: string; email: string };
export const AuthModal = ({ isOpen, onClose, onAuthenticated }: { isOpen: boolean; onClose: () => void; onAuthenticated: (account: Account) => void }) => {
 const [mode, setMode] = useState<"login" | "register">("login"), [show, setShow] = useState(false), [name, setName] = useState(""), [email, setEmail] = useState(""), [password, setPassword] = useState(""); if (!isOpen) return null;
 const submit = (e: React.FormEvent) => { e.preventDefault(); if (!email || !password || (mode === "register" && !name)) return; onAuthenticated({ name: mode === "register" ? name : email.split("@")[0], email }); onClose(); };
 return <div className="modal-backdrop"><section className="auth-modal" role="dialog" aria-modal="true" aria-label="Авторизация"><button className="modal-close" onClick={onClose}><X size={18} /></button><div className="auth-intro"><span className="brand-mark">L</span><p>Ваше пространство<br />для выбора университета.</p></div><div className="auth-form"><div><p className="auth-kicker">{mode === "login" ? "С возвращением" : "Новый профиль"}</p><h2>{mode === "login" ? "Войдите в Locus" : "Создайте аккаунт"}</h2></div><form onSubmit={submit}>{mode === "register" && <label>Имя<input autoFocus value={name} onChange={(e) => setName(e.target.value)} placeholder="Как к вам обращаться" required /></label>}<label>Email<input autoFocus={mode === "login"} value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="you@example.com" required /></label><label>Пароль<span className="password-wrap"><input value={password} onChange={(e) => setPassword(e.target.value)} type={show ? "text" : "password"} placeholder="Минимум 8 символов" minLength={8} required /><button type="button" onClick={() => setShow(!show)}>{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label><button className="form-primary">{mode === "login" ? "Войти" : "Создать аккаунт"}<ArrowRight size={17} /></button></form><p className="auth-switch">{mode === "login" ? "Впервые здесь?" : "Уже есть аккаунт?"}<button onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "Регистрация" : "Войти"}</button></p></div></section></div>;
};
