"use client";
import React, { useEffect, useRef, useState } from "react";
import { ArrowRight, Building2, Search, Sparkle, X } from "lucide-react";
import { POPULAR_SUGGESTIONS } from "@/lib/constants/universities";
export const HeroSearch = ({ onSearch, isLoading, currentQuery }: { onSearch: (name: string) => void; isLoading: boolean; currentQuery?: string }) => {
 const [value,setValue]=useState(currentQuery||""); const [open,setOpen]=useState(false); const [recent,setRecent]=useState<string[]>([]); const root=useRef<HTMLDivElement>(null);
 useEffect(()=>setValue(currentQuery||""),[currentQuery]); useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem("locus_recent_searches")||"[]"))}catch{}},[]); useEffect(()=>{const close=(e:MouseEvent)=>!root.current?.contains(e.target as Node)&&setOpen(false);document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);
 const results=POPULAR_SUGGESTIONS.filter(item=>`${item.name} ${item.city}`.toLowerCase().includes(value.toLowerCase())).slice(0,5); const remember=(name:string)=>{const next=[name,...recent.filter(item=>item!==name)].slice(0,5);setRecent(next);localStorage.setItem("locus_recent_searches",JSON.stringify(next))}; const pick=(name:string)=>{remember(name);setValue(name);setOpen(false);onSearch(name)}; const submit=(e:React.FormEvent)=>{e.preventDefault();if(value.trim()&&!isLoading)pick(value.trim())}; const shown=value?results:[...recent.map(name=>({name,query:`recent-${name}`,city:"Недавний поиск"})),...POPULAR_SUGGESTIONS.filter(item=>!recent.includes(item.name)).slice(0,5)];
 return <section id="top" className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" />Visual intelligence for education</div><h1><span className="hero-word word-1">Проверенный</span>{" "}<span className="hero-word word-2">визуальный профиль</span><br/><span className="hero-word word-3">университета</span>{" "}<span className="hero-word word-4">за 30 секунд.</span></h1><p className="hero-description">Собираем и проверяем визуальные материалы кампуса, чтобы решение о поступлении было чуть спокойнее и гораздо точнее.</p></div><div ref={root} className="search-area"><form onSubmit={submit} className="search-card"><Search size={19}/><input value={value} onChange={e=>{setValue(e.target.value);setOpen(true)}} onFocus={()=>setOpen(true)} placeholder="Название университета" disabled={isLoading}/>{value&&<button className="clear-button" type="button" onClick={()=>setValue("")}><X size={16}/></button>}<button className="search-submit" disabled={!value.trim()||isLoading}>{isLoading?"Анализируем":"Создать профиль"}<ArrowRight size={17}/></button></form>{open&&<div className="suggestions"><p>{value?"Подходящие университеты":"Недавние и популярные"}</p>{shown.length?shown.map(item=><button key={item.query} onClick={()=>pick(item.name)}><span><Building2 size={16}/>{item.name}</span><small>{item.city}</small></button>):value?<button onClick={()=>pick(value)}><span><Sparkle size={16}/>Проанализировать «{value}»</span></button>:null}</div>}<div className="search-note"><span>01</span> Поиск <i/><span>02</span> Проверка <i/><span>03</span> Профиль</div></div><div className="hero-visual" aria-hidden="true"><div className="visual-arch"/><div className="visual-sun"/><div className="visual-building"><span/><span/><span/><span/><span/><span/><span/><span/></div><div className="visual-caption">campus<br/><b>in focus</b></div></div></section>;
};
